### ISSUE TITLE
Should we just uncurry all the generated functions?

### ISSUE THREAD

**Issue by blinky3713** [f-o-a-m/purescript-web3-generator#11]
Right now we curry all the generated functions. For example, here's a `transferFrom` signature generated from an ERC-20 contract

```purescript
eth_transfer :: forall e p . 
                IsAsyncProvider p 
             => Maybe Address 
            -> Address 
            -> Address 
            -> (UIntN (D2 :& D5 :& D6)) 
            -> Web3 p e HexString
``` 

It's not event clear to me what is what here, there's like 3 `address` types and a `uint`. It turns out the first arg is the `from` field, the second is the `to` field, and the third is the `receiver` of the transfer as an argument to the contract. I think we could  do something similar to hs-web3, where instead we pass a `TransactionOptions` type and let the function complete it. So the signature would be:

```purescript
eth_transfer :: forall e p . 
                IsAsyncProvider p 
             => TransactionOptions
             -> Address 
             -> (UIntN (D2 :& D5 :& D6)) 
             -> Web3 p e HexString
``` 

Where then its clear that transaction options are taking care of the generic transaction information, and the other types are relevant for the function call. Maybe we can put a phantom type for the transaction options indicating the unit of currency as well, either `Wei` for payable functions or `NoPay` for non payable functions

**Comment by XertroV** [comment]
This seems like a good start to me. Along the lines of uncurrying (since there aren't _really_ any super useful partial applications) why not use a named record according to the interface? Afaik the hash used to decide methods to run in solidity is dependent on the named arguments so this should be safe. 

`{_from :: Address, _to :: Address, _tokenId :: UintN (D3 :& D2)}`

That sort of thing. You can still use the _ in records to make a curry-able web3 call if you want, too. 

I've had similar problems with my smart contracts, esp with multiple args of the same type.

**Comment by XertroV** [comment]
PS: that's for `transferFrom` I think. Not familiar with ERC721 abi and on phone so might be slightly off.

**Comment by XertroV** [comment]
Oh and 256 not 32 like I put (derp)

**Comment by blinky3713** [comment]
yeah, it was ERC20, sorry. 

Yeah i think this is probably a good idea as well. It might require a little work, but let me scope it out. I want ahead and implemented the `TransactionOptions` parrt just because we actually need that to move forward with that at work.

**Comment by XertroV** [comment]
> I want ahead and implemented the TransactionOptions parrt just because we actually need that to move forward with that at work.

👍  - sounds good. Also means that if we want to include extra parameters later on it's easy to factor into one nice data type.

**Comment by XertroV** [comment]
Oh man `TransactionOptions` is a must - just wasted an hour tracking down a bug because I called a contract method like `method (Just sendingAddress) contractAddress` instead of the other way around. IMO the from address should be the optional one - I'm never going to deploy a contract using a dataparam for another contract.

**Comment by blinky3713** [comment]
TransactionOptions is already in master, but not in a release. 

I have a PR in the main repo https://github.com/f-o-a-m/purescript-web3/pull/58 for the rest, this is what the generated code looks like for the `SimpleStorage` contract.

<img width="1026" alt="screen shot 2018-02-05 at 12 23 31 am" src="https://user-images.githubusercontent.com/31280145/35789585-2ddddb60-0a0b-11e8-8361-5fa840455515.png">

The first is a generated getter from the `public` keyword. These will always be curried because their args don't have names -- I thought about using numbered args but it seems over the top. The `setCount` method is as expected, using the type class + inference to enforce it rather than some really hacky solution using only the generator.

Does this seem reasonable?

**Comment by blinky3713** [comment]
The one caveat is that compilation time is now _suuuuuuuuuper_ slow, and it's taking an insane amount of cpu power to do all the contracts in this repo. In order to reduce this we really need to help the solver out, but haven't come up with anything yet.

**Comment by blinky3713** [comment]
maybe it's better to consider the `SimpleTupleStorage` contract

<img width="1292" alt="screen shot 2018-02-05 at 12 32 26 am" src="https://user-images.githubusercontent.com/31280145/35789735-1d9a6dee-0a0c-11e8-8999-abab8130b354.png">

**Comment by blinky3713** [comment]
if you remove the `ComplexStorage` abi, it's pretty quick again. something tells me it's a terrible function of the number of fields.

**Comment by blinky3713** [comment]
turns out the `RLProxy` wasn't necessary

**Comment by blinky3713** [comment]
#13

**Comment by XertroV** [comment]
Using records seems way nicer. 👍
