### ISSUE TITLE
[Idea] - Generated Contract Methods should always take 1 argument

### ISSUE THREAD

**Issue by XertroV** [f-o-a-m/purescript-web3-generator#31]
I have a fun situation: I'm parameterising web3 calls to avoid dropping transaction options everywhere.

Something like:

```purescript
type Web3Reqer m e a r = (TransactionOptions NoPay -> ChainCursor -> a -> Web3 e (Either CallError r)) -> ChainCursor -> a -> m e r
```

It occurs to me that I can't use this with some methods that take 0 arguments though. (Note: not sure if there's a clever way to express the possibility of 0 or 1 arguments in the `a ->` part of the signature)

One idea is to require an empty record (`Record ()` I think, not sure if `{}` works in signatures) so the call is `runWeb3 p $ myMethodNoArgs txOpts Latest {}`

The nice thing about this is _every_ method will now take txOpts, ChainCursor, and args in that order, and all args are records.

(Note: this doesn't work with methods that alter contracts since they don't take ChainCursor)

Anywhoo - just throwing ideas out there

----

The point of this, btw, is to allow a `contract` like thing to be passed around like you can in JS (the result of `web3.eth.contract(abi).at(addr)`) where you just pass in methods and the like.

**Comment by blinky3713** [comment]
Right now the module itself functions as the closest thing to the web3js `Contract` object. I would say that a `ReaderT TxOptions` stack could already be used to do what you're describing above, but i haven't tried. Have you considered this?

**Comment by XertroV** [comment]
> I would say that a ReaderT TxOptions stack could already be used to do what you're describing above, but i haven't tried. Have you considered this?

Nope. Thanks for the idea! Will look into that.

**Comment by XertroV** [comment]
@blinky3713 - neat, thanks

I'm using a bit more complex type atm: https://github.com/swarmfund/sv-voting-mvp/blob/master/pureSrc/SV/Light/Types/RunBallot.purs#L43

Here's how I use it: https://github.com/swarmfund/sv-voting-mvp/blob/master/pureSrc/SV/Light/AuditBallot.purs#L195

**Comment by XertroV** [comment]
Also, _very_ much looking forward to Chanterelle - will be great to write tests in purescript instead of JS. Keep up the great work :)

**Comment by blinky3713** [comment]
I'm closing this issue, but we are pretty happy with chanterelle and have made public announcements about it. check it out!
