### ISSUE TITLE
Deep nested types of `Vector n a` slows down (or maybe kills) `psc`

### ISSUE THREAD

**Issue by sectore** [f-o-a-m/purescript-web3-generator#41]
As an example here is random function `getAdopters()` written in `Solidity`
```solidity
address[16] public adopters;

function getAdopters() public view returns (address[16]) {
  return adopters;
}
```
It will be generated into `PureScript` as follow:
```purescript
type GetAdoptersFn = Tagged (SProxy "getAdopters()") (Tuple0 )

getAdopters :: forall e. TransactionOptions NoPay -> ChainCursor -> Web3 e (Either CallError (Vector (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (Z))))))))))))))))) Address))
getAdopters x0 cm = map unTuple1 <$> call x0 cm ((tagged $ Tuple0 ) :: GetAdoptersFn)
```

From a code _point of view_ everything is fine! However, the needed recursion to interpret that deep nested `(Vector (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (Z))))))))))))))))) Address)` type slows down `psc` and seems to kill it. In the example above ^ I could not compile the code anymore if a `Vector` has a size `> 14`.

The usage of `type` aliases  [`N1 .. N16`](https://github.com/f-o-a-m/purescript-web3/blob/master/src/Network/Ethereum/Web3/Solidity/Size.purs#L152-L168) could be a workaround. For example `(Vector N16 Address)` in my case. But then all `Vector`'s would have limited sizes of `1`..`16` and there might be a better solution. _I will think about it again..._.

**Comment by sectore** [comment]
> So if you use N16 which under the hood is still defined as S (... (Z) ...) is makes compilation faster?

Yep!

Will your approach cover all possible lengths of `Vector` or just up to a length of `16`? The question because if there are `Vector`s with more lengths...

**Comment by safareli** [comment]
Depending on max `N*` in ps-web3 which is `N16` now, we can just use this values in generated code. If length is more then 16, let's say 18, then generator could generate `S (S (16))`.

Note: `D1 :& D6` is not that easy to use instead of S/N as you need typelevel increment on it for `cons` to work

**Comment by sectore** [comment]
What about to generate those type aliases into each generated file as well? 

With that we would be independent of what in [Network/Ethereum/Web3/Solidity/Size.purs](https://github.com/f-o-a-m/purescript-web3/blob/master/src/Network/Ethereum/Web3/Solidity/Size.purs#L152-L168) is defined.

Note: We can't use a "single" type alias, such as:
```
type N16 = (S (S (S (S (S (S (S (S (S (S (S (S (S (S (S (Z))))))))))))))))
```
Instead of that ^ we have to generate all type alias _step by step_ from `Z` up to max length `N*`:
```
type N0 = Z
type N1 = S N0
type N2 = S N1
type N3 = S N2
type N4 = S N3
type N5 = S N4
type N6 = S N5
type N7 = S N6
type N8 = S N7
type N9 = S N8
type N10 = S N9
type N11 = S N10
type N12 = S N11
type N13 = S N12
type N14 = S N13
type N15 = S N14
type N16 = S N15
```
What do you think?

**Comment by blinky3713** [comment]
So did people ever look at https://github.com/bodil/purescript-typelevel? I decided to "vendor" parts of it for this project rather than depending on it because it had way more than we needed.

**Comment by safareli** [comment]
@sectore so I managed to write Increment for base 10 numbers

so will now will be adding tests and updating web3 libs

https://gist.github.com/safareli/1a5b6c415d9a86135af971d875de87b8#file-main-purs-L166
