### ISSUE TITLE
Nested vectors are printed incorrectly

### ISSUE THREAD

**Issue by srghma** [f-o-a-m/purescript-web3-generator#70]
`bytes2[4][3][]` should be printed as

`Array (Vector (DOne D3) (Vector (DOne D4) (BytesN (DOne D2))))`

but instead is printed as 

`Array (Vector (DOne D4) (Vector (DOne D3) (BytesN (DOne D2))))`

![2022-02-21-03pm-59-40-screenshot](https://user-images.githubusercontent.com/7573215/154969573-1cf42b9e-84d6-4f59-895d-3aa6563a1fde.png)

@martyall

**Comment by martyall** [comment]
Your interpretation seems to be correct, it should be an easy fix. We should also write a test to correct this

from https://docs.soliditylang.org/en/v0.8.11/types.html#arrays

> Arrays can have a compile-time fixed size, or they can have a dynamic size.

> The type of an array of fixed size k and element type T is written as T[k], and an array of dynamic size as T[].

> For example, an array of 5 dynamic arrays of uint is written as uint[][5]. The notation is reversed compared to some other languages. In Solidity, X[3] is always an array containing three elements of type X, even if X is itself an array. This is not the case in other languages such as C.

**Comment by martyall** [comment]
This was fixed in https://github.com/f-o-a-m/purescript-web3-generator/commit/d816fb2c17b24bc51e2384c6b4bf1c62b87556fb
