### ISSUE TITLE
Generated module names can be invalid and other issues (Discussion)

### ISSUE THREAD

**Issue by XertroV** [f-o-a-m/purescript-web3-generator#9]
I noticed that generating ABI stuff can be fiddly because the module names are autogenerated without reference to the path of the file.

Eg:

* I have './abi/myContract.json'
* I want the generated purs file in `./someSrc/Project/Contracts/MyContract.purs`
* I set the output dir to `./someSrc/Project/Contracts`

If I run the generator then `myContract.purs` will be generated (no capital) and the module name is `Contracts.myContract` (which is invalid)

Additionally, the generated file is in `./someSrc/Project/Contracts/Contracts/`

Suggestions: 
* throw an error if the `myContract.json` file doesn't start with a capital, or autocapitalise
* allow setting a module prefix (e.g. `Project.Contracts`)
* don't generate the file in an undocumented `Contracts` folder
* Alternatively: update docs

------

While updating the docs is good anyway, I think the intention of how this should be used needs to be made clearer in the tool itself - the design of the tool itself can be improved.

Example: maybe it's better to generate files in a separate src directory (e.g. contractSrc) and then use `-I` with `pulp` to include them. This would eliminate the module name problem above, I think.

Anyway, wanted to post this to start a discussion about the best way to handle this atm.

**Comment by blinky3713** [comment]
We are sort of half way there with the "GeneratorOptions" being passed around (which should be put in a `Reader` environment in the next refactor). It seems like a few of these concerns could be addressed there.

Things that seem important are

 - [ ] always generator proper purescript module names (i.e. capitalized)
 - [ ] the module prefixes should respect the abi source directory heirarchy, as should the generated directory containing the purescript files

I'm not familiar with this `-I` flag, can you say more about what that would look like?

**Comment by kejace** [comment]
Relevant flags from running `pulp build --help` are:

```
--include -I <dir:dir:...>  Additional directories for PureScript source files, separated by `:`.
--src-path <dir>            Directory for PureScript source files. [Default: "src"]
```

`-I` would let you have both `src/` and `contracts/` directories.

I agree with the points made here and think we should make the (breaking) changes in the next release.

**Comment by XertroV** [comment]
> I agree with the points made here and think we should make the (breaking) changes in the next release.

Awesome!

For the moment I've worked around the above by using `-I` (include dir) on a `Contracts` directory and I manually fiddle with the file names or module names. Seems to work okay atm.

**Comment by safareli** [comment]
So this is what we are going to do (comment if there are any objections):
- let generator take module prefixes as argument which by default will be `Contracts`
- let generator take project path as argument which by default will be `src`
  (path to the contracts will be generated by `split "."` of module prefix and appending to project path)
- if name of some abi file is not valid fail the generation instead of auto-fixing it, so it's noticed as early as possible. Also we don't wanna auto-fix as for example one might have `abi/foo.json` as well as `abi/Foo.json` and if we take responsibility to fix names we should do more staff for little gain.

**Comment by blinky3713** [comment]
👍

**Comment by blinky3713** [comment]
My only request is that you also update the README when you're done

**Comment by safareli** [comment]
sure thing
